import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond, Cinzel } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar';
import MobileNav from '@/components/MobileNav';
import BackgroundImageHandler from '@/components/ui/BackgroundImageHandler';
import { getMenuData } from '@/lib/menu-data';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const menuItems = await getMenuData();
  return (
    <html lang="en">
      <body className={`flex ${geistSans.variable} ${geistMono.variable} ${ebGaramond.variable} ${cinzel.variable} antialiased`}>
        <BackgroundImageHandler />
        <Sidebar />
        <MobileNav items={menuItems} />
        {/* ml-72 pushes the content to the right of the 72-unit wide sidebar */}
        <div className="flex-1 md:ml-72 w-full min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}